version: '3.5'
services:
  mongodb:
    image: mongo:latest
    # Not using for simulation purposes
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container