version: '3.2'
services:  
  datagenerator:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.python
    volumes:      
    #Use this only for development
      - ../etlapp/:/app/etlapp
    command: etlapp.emitter
    env_file: ./temperature.env

  collector:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.flask    
    volumes:      
      #Use this only for development
      - ../etlapp/:/app/etlapp 
    env_file: ./temperature.env
    environment:
      - MODULE_NAME=etlapp.collector.flask_collector
      - LOG_LEVEL=DEBUG

  datamapper:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.python    
    volumes:      
      #Use this only for development
      - ../etlapp/:/app/etlapp
    env_file: ./temperature.env
    command: etlapp.datamapper.mapper
  
  datawriter:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.python    
    volumes:      
      #Use this only for development
      - ../etlapp/:/app/etlapp
    env_file: ./temperature.env
    command: etlapp.datawriter.influxdb_writer
    
