version: '3.5'
services:  
  datamapper:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.python    
    # volumes:      
      #Use this only for development
      # - ../etlapp/:/app/etlapp
    env_file: ./temperature.env
    command: etlapp.datamapper
  
  datawriter:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.python    
    # volumes:      
      #Use this only for development
      # - ../etlapp/:/app/etlapp
    env_file: ./temperature.env
    command: etlapp.datawriter
    
